DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
SOLVER:
  BASE_LR: 0.1
  LR_MILESTONES: [15, 30]
  MAX_EPOCHS: 45
  TRAIN_BATCH_SIZE: 128
  WARMUP: False
  WARMUP_EPOCH: 10
  WARMUP_FACTOR: 0.1
ISON:
  DEPTH: 18
  ORTHO_COEFF: 0.0
  HAS_BN: False
  HAS_ST: False
  SReLU: True