DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
SOLVER:
  BASE_LR: 0.01
  LR_MILESTONES: [20, 40]
  MAX_EPOCHS: 50
  TRAIN_BATCH_SIZE: 128
  WARMUP: False
  WARMUP_EPOCH: 10
  WARMUP_FACTOR: 0.1
  DISAG_COEFF: 0.00005