DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
  NORMALIZE: True
SOLVER:
  BASE_LR: 0.01
  LR_MILESTONES: [120, 240]
  MAX_EPOCHS: 300
  TRAIN_BATCH_SIZE: 128
  WARMUP: True
  WARMUP_EPOCH: 10
  WARMUP_FACTOR: 0.1
  TRADES: True
ISON:
  DEPTH: 18
  ORTHO_COEFF: 0.1
  HAS_BN: False
  HAS_ST: False
  SReLU: True